using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unity.AssetManager.Core.Editor")]
[assembly: InternalsVisibleTo("Unity.AssetManager.Upload.Editor")]
[assembly: InternalsVisibleTo("Unity.AssetManager.Core.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.AssetManager.UI.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.AssetManager.Upload.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Cloud.Assets.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Assets.Runtime.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Common.Editor.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Common.Runtime.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Identity.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Identity.Editor.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.Identity.Runtime.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.AppLinking.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.AppLinking.Editor.Embedded")]
[assembly: InternalsVisibleTo("Unity.Cloud.AppLinking.Runtime.Embedded")]
